### ISSUE TITLE
Action does not create site on forge

### ISSUE THREAD

**Issue by GlitchWitch** [bakerkretzmar/laravel-deploy-preview#15]
I am attempting to set this up in an existing repo but am not having much success.

I've used the following action config

```
# deploy-preview.yml
name: Deploy Preview
on:
  pull_request:
    types: [opened, closed, reopened, synchronize]
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bakerkretzmar/laravel-deploy-preview@v2
        with:
          forge-token: ${{ secrets.FORGE_TOKEN }}
          servers: |
            dev.app.REDACTEDORG.com 728116
```

And while the action seems to complete without error, no new site is created on the target forge server.

![image](https://github.com/bakerkretzmar/laravel-deploy-preview/assets/32590246/01a66471-4f25-408f-8a2a-eb45e49f112d)

I have attempted the following steps to troubleshoot

- Recreated the `FORGE_TOKEN`
- Recreated the server
- Attempted to use older `laravel-deploy-preview@v1.1.0`
- Ensured server can deploy from repo manually

I've attached the full output of the latest action run [here](https://github.com/bakerkretzmar/laravel-deploy-preview/files/13061405/2023-10-21T17.30.16-action.log) but sadly there isn't much in the way of useful information.

Any help or direction would be much appreciated!
