### ISSUE TITLE
Workflow fails with 404 "Resource not found" response from Forge API

### ISSUE THREAD

**Issue by noahc3** [bakerkretzmar/laravel-deploy-preview#50]
_Continuing the conversation from https://github.com/bakerkretzmar/laravel-deploy-preview/issues/49#issuecomment-2542132266 in a dedicated issue_

When trying to deploy a new site, the workflow fails with a 404 error from the Forge API. This is happening on v2.7.0 and v2.7.1. Reverting to 2.5.2 resolves the issue. We've had our version of the workflow pinned since June so we never tested 2.6.0, so it seems like either 2.6.0 or 2.7.0 introduced a change that's causing this.

Here is our workflow yaml contents ( `after-deploy` and `environment` removed for brevity):

<details>
  <summary>Workflow yaml contents (click to expand)</summary>
  

```
name: Deploy Preview

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GlitchSecure/laravel-deploy-preview@main
        with:
          forge-token: ${{ secrets.FORGE_TOKEN }}
          servers: |
            ${{ secrets.FORGE_PREVIEW_SERVERS }}
          existing-certificate: |
            ${{ secrets.SSL_CERTIFICATE }}
          existing-certificate-key: |
            ${{ secrets.SSL_PRIVATE_KEY }}
          no-certificate: false
          after-deploy: |
            $FORGE_PHP artisan down
            [[ snip ]]
          environment: |
            APP_ENV=development
            [[ snip ]]
```
  
</details>

([Our forked repository](https://github.com/GlitchSecure/laravel-deploy-preview) that we reference in the file matches 1:1 with your main branch, we just fork it to pin the version.)

The error in question:

```
Creating preview site for branch: oauth-error-context.
Creating site: oauth-error-context.dev.app.glitchsecure.com.
"Resource not found."
Error: Forge API request failed with status code 404.
```

In Forge, a generic deploy error is generated but no helpful information. We confirmed there is no issue with server connectivity.

![image](https://github.com/user-attachments/assets/fc39fad8-5a72-4d52-a2ce-4822edeb7eaa)

I can also see that the database got created, but thats about it. The site never gets created. The Forge event log ends at "Deploying Default Site Page":

![image](https://github.com/user-attachments/assets/1d4b672c-f6e2-4039-b1e8-530b9253efe0)

Oddly I can't click the logs button for the "Deploying Default Site Page" event. It doesn't usually have much output, but usually you can at least click the log button and see "This event has no output."

Running the workflow with debug logging enabled, the workflow gets to the point of polling the `/servers/748442/sites/2560138` endpoint, which succeeds several times, but eventually returns a 404 which is when the workflow aborts (sensitive info redacted)

<details>
  <summary>Workflow debug log (click to expand)</summary>
  
  ```
[[ a few more duplicate requests before this ]]
> GET /servers/748442/sites/2560138
< GET /servers/748442/sites/2560138 200 OK
{
  site: {
    id: 2560138,
    server_id: 748442,
    name: 'oauth-error-context.dev.app.glitchsecure.com',
    aliases: [],
    directory: '/public',
    wildcards: false,
    status: 'installing',
    repository: null,
    repository_provider: null,
    repository_branch: null,
    repository_status: null,
    quick_deploy: false,
    deployment_status: null,
    project_type: 'php',
    php_version: 'php82',
    app: null,
    app_status: null,
    slack_channel: null,
    telegram_chat_id: null,
    telegram_chat_title: null,
    teams_webhook_url: null,
    discord_webhook_url: null,
    failure_deployment_emails: [[ redacted ]],
    created_at: '2024-12-13 20:52:16',
    username: '',
    deployment_url: [[ redacted ]],
    is_secured: false,
    web_directory: '/home//oauth-error-context.dev.app.glitchsecure.com/public',
    tags: []
  }
}
> GET /servers/748442/sites/2560138
< GET /servers/748442/sites/2560138 200 OK
{
   [[ same as above ]]
  }
}
> GET /servers/748442/sites/2560138
< GET /servers/748442/sites/2560138 200 OK
{
  [[ same as above ]]
}
> GET /servers/748442/sites/2560138
< GET /servers/748442/sites/2560138 404 Not Found
Resource not found.
"Resource not found."
```
  
</details>

I went through the other logs available in Forge but didn't find much else that was relevant. In particular the SSH auth logs show Forge is connecting via SSH just fine without any errors. 

Let me know if there's anything else I can check for you.
